### ISSUE TITLE
Update concepts page

### ISSUE THREAD

**Issue by tjohn123456** [awsdocs/aws-codeartifact-user-guide#12]
Please update the "package" definition in AWS CodeArtifact [concepts](https://docs.aws.amazon.com/codeartifact/latest/ug/codeartifact-concepts.html#welcome-concepts-package) page to include NuGet as a package manager supported.

**Comment by tjohn123456** [comment]
Created a pull request with fix. Since I don't have write permission to the repo, I am unable to link this PR I created with the fix to this issue. See https://github.com/awsdocs/aws-codeartifact-user-guide/pull/11

**Comment by tjohn123456** [comment]
@tjohn123456 issue created

**Comment by elijahbatkoski** [comment]
Closing this as the PR is merged, thanks again @tjohn123456 !
