### ISSUE TITLE
Automatic Maven Repository Authorization Token Extension

### ISSUE THREAD

**Issue by brcolow** [awsdocs/aws-codeartifact-user-guide#20]
Hi,

Some time ago a user on StackOverflow [asked about automatically refreshing the Codeartifact authorization token](https://stackoverflow.com/questions/65791229/aws-codeartifact-token-update/72022249#72022249). I found this question because I too was looking for the answer as I prefer having everything "just work" with a single `mvn deploy`.

I made [an extension](https://github.com/brcolow/codeartifact-maven-extension) to automatically fetch an authorization token and configure Maven to use Codeartifact as the repository. As noted in the Stackoverflow, it's not very flexible at the moment with regards to how it expects things to be setup (Maven central mirror, IAM profile in credentials file, etc.) but I think it's a decent first step at making this "pain point" of using CodeArtifact (not trying to make a mountain out of a mole hill, I just don't like the user experience of having to manually refresh a token every 12 hours) with Maven go away. If there is any interest from anyone with any particular use cases we could make it more flexible and then it may be worth a mention, if deemed so worthy (:)) on the Maven configuration user guide.

Cheers.

**Comment by jessicrj** [comment]
Thank you for your request, @brcolow. I'll add it to the team's list of items for future consideration.
