### ISSUE TITLE
Twine link broken

### ISSUE THREAD

**Issue by maanisim** [awsdocs/aws-codeartifact-user-guide#21]
Hello there,

When checking the documentation [Configure and use pip with CodeArtifact](https://docs.aws.amazon.com/codeartifact/latest/ug/python-configure-pip.html#python-run-pip). I can see the following snippet:

```
Configure twine by following the steps in [Configure and use pip with CodeArtifact](https://docs.aws.amazon.com/codeartifact/latest/ug/python-configure-pip.html).
```

When attempting to click `Configure and use pip with CodeArtifact` nothing happens as it redirects to the same page, please modify it to a working link which I assume it should be: https://docs.aws.amazon.com/codeartifact/latest/ug/python-configure-twine.html

**Comment by jessicrj** [comment]
Thank you for telling us about this issue, @michalani. The link has been fixed and will show in the next refresh coming soon. Nice catch!
