### ISSUE TITLE
Documentation deleted

### ISSUE THREAD

**Issue by HermannGruber** [awsdocs/aws-codeartifact-user-guide#22]
With the last commit c771d14886c1bcc7fa87932aec787cb3af029288, all of the documentation was deleted. Was this on purpose? Where can I find the information now?

**Comment by jessicrj** [comment]
Hello Hermann. Thank you for bringing this to my attention, as the documentation being removed was unintentional. All documentation has been returned and updated. 

Thanks again for reaching out.
-Jessica
